// src/app/dashboard/agenda/page.tsx
'use client';

import { useState, useMemo } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import {
  addMonths,
  subMonths,
  format,
  startOfMonth,
  endOfMonth,
  startOfWeek,
  endOfWeek,
  eachDayOfInterval,
  isSameMonth,
  isToday,
  isSameDay,
} from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { ChevronLeft, ChevronRight, Clock, MapPin, Phone, User, Plus, Pencil, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { useToast } from '@/hooks/use-toast';
import { ScrollArea } from '@/components/ui/scroll-area';
import { useSettings } from '@/contexts/SettingsContext';

// Define the structure for a single appointment
type Appointment = {
  id: string;
  time: string;
  clientName: string;
  address: string;
  phone?: string;
  contact: string;
};

// Define the schema for the appointment form using Zod
const appointmentSchema = z.object({
  clientName: z.string().min(1, 'O nome do cliente é obrigatório.'),
  address: z.string().min(1, 'O endereço é obrigatório.'),
  phone: z.string().optional(),
  contact: z.string().min(1, 'O nome do contato na visita é obrigatório.'),
  time: z.string().min(1, 'O horário é obrigatório.'),
});

type AppointmentFormValues = z.infer<typeof appointmentSchema>;

export default function AgendaPage() {
  const [currentMonth, setCurrentMonth] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingAppointment, setEditingAppointment] = useState<Appointment | null>(null);
  const [selectedAppointment, setSelectedAppointment] = useState<Appointment | null>(null);
  const [appointmentToDelete, setAppointmentToDelete] = useState<Appointment | null>(null);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [appointmentForReminder, setAppointmentForReminder] = useState<Appointment | null>(null);


  const [appointments, setAppointments] = useState<Record<string, Appointment[]>>({
    [format(new Date(), 'yyyy-MM-dd')]: [
        { id: '1', time: '10:00', clientName: 'Tech Solutions', address: 'Rua das Inovações, 123', phone: '1199999999', contact: 'Ana' },
    ]
  });
  const { toast } = useToast();
  const { companyProfile } = useSettings();

  const form = useForm<AppointmentFormValues>({
    resolver: zodResolver(appointmentSchema),
    defaultValues: {
      clientName: '',
      address: '',
      phone: '',
      contact: '',
      time: '',
    },
  });

  const monthStart = startOfMonth(currentMonth);
  const monthEnd = endOfMonth(monthStart);
  const startDate = startOfWeek(monthStart, { locale: ptBR, weekStartsOn: 0 });
  const endDate = endOfWeek(monthEnd, { locale: ptBR, weekStartsOn: 0 });

  const days = eachDayOfInterval({ start: startDate, end: endDate });
  const weekdays = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'];

  const handlePrevMonth = () => {
    setCurrentMonth(subMonths(currentMonth, 1));
  };

  const handleNextMonth = () => {
    setCurrentMonth(addMonths(currentMonth, 1));
  };

  const openModalForDay = (day: Date) => {
    setSelectedDate(day);
    form.reset({
      clientName: '',
      address: '',
      phone: '',
      contact: '',
      time: '',
    });
    setEditingAppointment(null);
    setSelectedAppointment(null);
    setIsModalOpen(true);
  };
  
  const handleDayClick = (day: Date) => {
    if (isSameMonth(day, currentMonth)) {
        openModalForDay(day);
    }
  };

  const handleEditClick = (appointment: Appointment) => {
    setEditingAppointment(appointment);
    form.reset({
      clientName: appointment.clientName,
      address: appointment.address,
      phone: appointment.phone || '',
      contact: appointment.contact,
      time: appointment.time,
    });
  };

  const handleDeleteClick = (appointment: Appointment) => {
    setAppointmentToDelete(appointment);
    setIsDeleteDialogOpen(true);
  };

  const confirmDelete = () => {
    if (!appointmentToDelete) return;
    
    const dateKey = format(selectedDate, 'yyyy-MM-dd');
    setAppointments(prev => ({
        ...prev,
        [dateKey]: prev[dateKey].filter(app => app.id !== appointmentToDelete.id),
    }));

    toast({
        title: "Agendamento Excluído!",
        description: `O compromisso com ${appointmentToDelete.clientName} foi removido.`,
        variant: "destructive"
    });
    setIsDeleteDialogOpen(false);
    setAppointmentToDelete(null);
  };

  const handleCancelEdit = () => {
    setEditingAppointment(null);
    setSelectedAppointment(null);
    form.reset({
      clientName: '',
      address: '',
      phone: '',
      contact: '',
      time: '',
    });
  }

  const handleSendWhatsAppReminder = () => {
    if (!appointmentForReminder) return;

    const { clientName, time, phone } = appointmentForReminder;
    const dateStr = format(selectedDate, 'dd/MM/yyyy', { locale: ptBR });

    const message = `Olá, ${clientName}! 👋\n\nEste é um lembrete do seu agendamento com a ${companyProfile.name} no dia ${dateStr} às ${time}.\n\nAté breve!`;
    
    const encodedMessage = encodeURIComponent(message);
    
    const cleanPhone = phone?.replace(/\D/g, '') || '';
    let whatsappUrl = `https://api.whatsapp.com/send?text=${encodedMessage}`;

    if (cleanPhone.length >= 10) {
        const phoneWithCountryCode = cleanPhone.length > 11 ? cleanPhone : `55${cleanPhone}`;
        whatsappUrl = `https://api.whatsapp.com/send?phone=${phoneWithCountryCode}&text=${encodedMessage}`;
    }

    window.open(whatsappUrl, '_blank', 'noopener,noreferrer');

    toast({
        title: "Pronto para Enviar!",
        description: `Sua mensagem para ${clientName} está pronta no WhatsApp.`,
    });

    setAppointmentForReminder(null); // Close the dialog
  };

  function onSubmit(values: AppointmentFormValues) {
    const dateKey = format(selectedDate, 'yyyy-MM-dd');
    let savedAppointment: Appointment;
    
    if (editingAppointment) {
        // Update existing appointment
        const updatedAppointment: Appointment = {
            id: editingAppointment.id,
            time: values.time,
            clientName: values.clientName,
            address: values.address,
            phone: values.phone,
            contact: values.contact,
        };
        savedAppointment = updatedAppointment;
        setAppointments(prev => {
            const dayAppointments = prev[dateKey].map(app => 
                app.id === editingAppointment.id ? updatedAppointment : app
            );
            dayAppointments.sort((a, b) => a.time.localeCompare(b.time));
            return { ...prev, [dateKey]: dayAppointments };
        });
        toast({
            title: 'Agendamento Atualizado!',
            description: `Visita para ${values.clientName} atualizada.`,
        });
    } else {
        // Create new appointment
        const newAppointment: Appointment = {
            id: new Date().toISOString(),
            time: values.time,
            clientName: values.clientName,
            address: values.address,
            phone: values.phone,
            contact: values.contact,
        };
        savedAppointment = newAppointment;

        setAppointments(prev => {
            const dayAppointments = prev[dateKey] ? [...prev[dateKey], newAppointment] : [newAppointment];
            dayAppointments.sort((a, b) => a.time.localeCompare(b.time));
            return { ...prev, [dateKey]: dayAppointments };
        });

        toast({
            title: 'Agendamento Criado!',
            description: `Visita para ${values.clientName} agendada para as ${values.time}.`,
        });
    }

    setEditingAppointment(null);
    setSelectedAppointment(null);
    form.reset({
      clientName: '',
      address: '',
      phone: '',
      contact: '',
      time: '',
    });
    
    setAppointmentForReminder(savedAppointment);
  }

  const selectedDayAppointments = useMemo(() => {
    const dateKey = format(selectedDate, 'yyyy-MM-dd');
    return appointments[dateKey] || [];
  }, [selectedDate, appointments]);

  return (
    <>
      <div className="flex h-full flex-col bg-card shadow-xl rounded-2xl p-6 text-card-foreground">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <div>
              <h2 className="text-2xl font-bold capitalize text-foreground">
                {format(currentMonth, 'MMMM', { locale: ptBR })}
              </h2>
              <p className="text-lg text-muted-foreground">{format(currentMonth, 'yyyy')}</p>
            </div>
            <div className="flex items-center gap-1">
              <Button variant="ghost" size="icon" onClick={handlePrevMonth} className="rounded-lg h-10 w-10 hover:bg-accent/50">
                <ChevronLeft className="h-5 w-5" />
              </Button>
              <Button variant="ghost" size="icon" onClick={handleNextMonth} className="rounded-lg h-10 w-10 hover:bg-accent/50">
                <ChevronRight className="h-5 w-5" />
              </Button>
            </div>
          </div>

          {/* Calendar Grid */}
          <div className="grid flex-1 grid-cols-7 text-center">
            {/* Weekdays */}
            {weekdays.map((day, i) => (
              <div key={i} className="flex items-center justify-center text-sm font-medium text-muted-foreground py-2 border-b">
                {day}
              </div>
            ))}

            {/* Days */}
            {days.map((day) => {
              const dayKey = format(day, 'yyyy-MM-dd');
              const dayEvents = appointments[dayKey] || [];
              return (
                <div
                  key={day.toString()}
                  className={cn(
                    "flex flex-col items-center justify-start p-2 border-t border-l",
                    "aspect-[10/7] min-h-0",
                    isSameMonth(day, currentMonth) ? 'cursor-pointer' : 'bg-muted/30'
                  )}
                  onClick={() => handleDayClick(day)}
                >
                  <div
                    className={cn(
                      "w-8 h-8 flex items-center justify-center rounded-full transition-colors text-base font-medium",
                      !isSameMonth(day, currentMonth) && 'text-muted-foreground/50',
                      !isSameDay(day, selectedDate) && isSameMonth(day, currentMonth) && 'hover:bg-accent/50',
                      isSameDay(day, selectedDate) && 'bg-primary text-primary-foreground',
                      isToday(day) && !isSameDay(day, selectedDate) && 'border-2 border-primary/50'
                    )}
                  >
                    {format(day, 'd')}
                  </div>
                  {isSameMonth(day, currentMonth) && (
                    <div className="flex items-center gap-1 mt-2 h-2">
                      {dayEvents.slice(0, 3).map((event, index) => (
                        <div key={index} className={cn("w-2 h-2 rounded-full", ["bg-chart-1", "bg-chart-2", "bg-chart-3"][index % 3])}></div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
      </div>

      <Dialog open={isModalOpen} onOpenChange={(isOpen) => {
          if (!isOpen) {
              setEditingAppointment(null);
              setSelectedAppointment(null);
              form.reset({
                clientName: '',
                address: '',
                phone: '',
                contact: '',
                time: '',
              });
          }
          setIsModalOpen(isOpen);
      }}>
        <DialogContent className="sm:max-w-[425px] md:max-w-3xl flex flex-col h-[90vh]">
          <DialogHeader className='flex-none'>
            <DialogTitle>
              Agenda para {format(selectedDate, 'dd/MM/yyyy', { locale: ptBR })}
            </DialogTitle>
            <DialogDescription>
              Visualize, adicione ou edite compromissos para este dia.
            </DialogDescription>
          </DialogHeader>
          <div className="grid flex-1 grid-cols-1 md:grid-cols-2 gap-6 py-4 overflow-y-auto">
            {/* Existing Appointments */}
            <div className="space-y-4">
                 <h3 className="font-semibold text-lg text-foreground">Compromissos Agendados</h3>
                 <ScrollArea className="h-full pr-4">
                    {selectedDayAppointments.length > 0 ? (
                        <div className="space-y-4">
                            {selectedDayAppointments.map(app => (
                                <div 
                                    key={app.id} 
                                    className={cn(
                                        "relative group p-3 bg-muted/50 rounded-lg text-sm space-y-2 cursor-pointer",
                                        selectedAppointment?.id === app.id && !editingAppointment && "ring-2 ring-primary"
                                    )}
                                    onClick={() => {
                                        if (!editingAppointment) {
                                            setSelectedAppointment(app)
                                        }
                                    }}
                                >
                                    <div className="flex justify-between items-start">
                                        <p className="font-semibold text-base pr-16">{app.clientName}</p>
                                        <div className="flex items-center gap-2 text-primary font-bold">
                                            <Clock className="h-4 w-4"/>
                                            {app.time}
                                        </div>
                                    </div>
                                    <p className="text-muted-foreground flex items-center gap-2"><MapPin className="h-4 w-4"/>{app.address}</p>
                                    <p className="text-muted-foreground flex items-center gap-2"><User className="h-4 w-4"/>{app.contact}</p>
                                    {app.phone && <p className="text-muted-foreground flex items-center gap-2"><Phone className="h-4 w-4"/>{app.phone}</p>}
                                    
                                    <div className="absolute top-2 right-2 flex items-center opacity-0 group-hover:opacity-100 transition-opacity bg-muted/80 rounded-md">
                                        <Button variant="ghost" size="icon" className="h-7 w-7 text-destructive hover:text-destructive" onClick={() => handleDeleteClick(app)}>
                                            <Trash2 className="h-4 w-4" />
                                        </Button>
                                    </div>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center h-full text-center text-muted-foreground border-2 border-dashed rounded-lg p-8">
                            <p>Nenhum compromisso para este dia.</p>
                            <p className="text-xs">Use o formulário para adicionar um.</p>
                        </div>
                    )}
                 </ScrollArea>
            </div>
            {/* New/Edit Appointment Form */}
            <div>
                 <h3 className="font-semibold text-lg text-foreground mb-4">{editingAppointment ? 'Editar Agendamento' : 'Novo Agendamento'}</h3>
                 <Form {...form}>
                    <form id="appointment-form" onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                        <FormField
                        control={form.control}
                        name="time"
                        render={({ field }) => (
                            <FormItem>
                            <FormLabel>Horário</FormLabel>
                            <FormControl>
                                <Input type="time" {...field} />
                            </FormControl>
                            <FormMessage />
                            </FormItem>
                        )}
                        />
                        <FormField
                        control={form.control}
                        name="clientName"
                        render={({ field }) => (
                            <FormItem>
                            <FormLabel>Nome do Cliente</FormLabel>
                            <FormControl>
                                <Input placeholder="Ex: Tech Solutions Ltda." {...field} />
                            </FormControl>
                            <FormMessage />
                            </FormItem>
                        )}
                        />
                        <FormField
                        control={form.control}
                        name="address"
                        render={({ field }) => (
                            <FormItem>
                            <FormLabel>Endereço</FormLabel>
                            <FormControl>
                                <Input placeholder="Ex: Rua das Inovações, 123" {...field} />
                            </FormControl>
                            <FormMessage />
                            </FormItem>
                        )}
                        />
                        <FormField
                        control={form.control}
                        name="phone"
                        render={({ field }) => (
                            <FormItem>
                            <FormLabel>Telefone de Contato</FormLabel>
                            <FormControl>
                                <Input placeholder="(00) 00000-0000" {...field} value={field.value || ''}/>
                            </FormControl>
                            <FormMessage />
                            </FormItem>
                        )}
                        />
                        <FormField
                        control={form.control}
                        name="contact"
                        render={({ field }) => (
                            <FormItem>
                            <FormLabel>Contato na Visita</FormLabel>
                            <FormControl>
                                <Input placeholder="Ex: Sr. Carlos" {...field} />
                            </FormControl>
                            <FormMessage />
                            </FormItem>
                        )}
                        />
                    </form>
                </Form>
            </div>
          </div>
          <DialogFooter className="flex-none pt-4 gap-2 border-t">
              {editingAppointment ? (
                <>
                    <Button type="button" variant="outline" onClick={handleCancelEdit}>Cancelar</Button>
                    <Button type="submit" form="appointment-form">Salvar Alterações</Button>
                </>
              ) : (
                <>
                    {selectedAppointment && (
                        <Button type="button" variant="outline" onClick={() => handleEditClick(selectedAppointment)}>
                            <Pencil className="mr-2 h-4 w-4" />
                            Editar
                        </Button>
                    )}
                    <Button type="submit" form="appointment-form">
                        <Plus className="mr-2 h-4 w-4" />
                        Agendar
                    </Button>
                </>
              )}
        </DialogFooter>
        </DialogContent>
      </Dialog>
      
      <AlertDialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <AlertDialogContent>
            <AlertDialogHeader>
            <AlertDialogTitle>Você tem certeza absoluta?</AlertDialogTitle>
            <AlertDialogDescription>
                Essa ação não pode ser desfeita. Isso excluirá permanentemente o compromisso com <span className="font-medium">{appointmentToDelete?.clientName}</span>.
            </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setAppointmentToDelete(null)}>Cancelar</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete}>Confirmar Exclusão</AlertDialogAction>
            </AlertDialogFooter>
        </AlertDialogContent>
    </AlertDialog>

    <AlertDialog open={!!appointmentForReminder} onOpenChange={(isOpen) => !isOpen && setAppointmentForReminder(null)}>
        <AlertDialogContent>
            <AlertDialogHeader>
                <AlertDialogTitle>Agendamento Concluído!</AlertDialogTitle>
                <AlertDialogDescription>
                    Deseja enviar um lembrete via WhatsApp para o cliente{" "}
                    <span className="font-medium">{appointmentForReminder?.clientName}</span>?
                </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
                <AlertDialogCancel onClick={() => setAppointmentForReminder(null)}>Não, obrigado</AlertDialogCancel>
                <AlertDialogAction onClick={handleSendWhatsAppReminder}>Enviar Lembrete</AlertDialogAction>
            </AlertDialogFooter>
        </AlertDialogContent>
    </AlertDialog>
    </>
  );
}

// laravel-app/resources/js/Pages/Agenda.vue
<script setup>
import { computed, reactive, ref, watch } from 'vue';
import { Head, router, useForm, usePage } from '@inertiajs/vue3';
import axios from 'axios';
import {
    addMonths, subMonths, format, startOfMonth, endOfMonth, startOfWeek, endOfWeek,
    eachDayOfInterval, isSameMonth, isToday, isSameDay, parseISO,
} from 'date-fns';
import { ptBR } from 'date-fns/locale';
import {
    ChevronLeft, ChevronRight, Clock, MapPin, Phone, User, Pencil, Trash2, Briefcase,
    Calendar as CalendarIcon, CheckCircle2, XCircle, CalendarPlus, CalendarClock, Loader2,
    Search, Send, BellRing, Ban, AlertTriangle, Check,
} from 'lucide-vue-next';
import AppLayout from '@/Layouts/AppLayout.vue';
import { Button } from '@/Components/ui/button';
import {
    Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from '@/Components/ui/dialog';
import {
    AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent,
    AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle,
} from '@/Components/ui/alert-dialog';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import { ScrollArea } from '@/Components/ui/scroll-area';
import { Popover, PopoverContent, PopoverTrigger } from '@/Components/ui/popover';
import { Textarea } from '@/Components/ui/textarea';
import { Badge } from '@/Components/ui/badge';
import { Checkbox } from '@/Components/ui/checkbox';
import { useToast } from '@/composables/useToast';
import { cn, formatPhoneNumber } from '@/lib/utils';

defineOptions({ layout: AppLayout });

const props = defineProps({
    appointments: Array,
    customers: Array,
    sectors: Array,
    users: Array,
});
const { toast } = useToast();
const page = usePage();

const isAdmin = computed(() => page.props.auth.user?.role === 'admin');

const currentMonth = ref(new Date());
const selectedDate = ref(new Date());
const isModalOpen = ref(false);
const editingAppointment = ref(null);
const selectedAppointment = ref(null);
const appointmentToDelete = ref(null);
const isDeleteDialogOpen = ref(false);
const searchTermAssignees = ref('');
const isJustificationDialogOpen = ref(false);
const appointmentToProcess = ref(null);
const justification = ref('');
const isCustomerSearchOpen = ref(false);
const sentMessageIndexes = ref([]);

const notificationState = reactive({ isOpen: false, isLoading: false, isSimulated: false, details: [] });

const defaultValues = { date: format(new Date(), 'yyyy-MM-dd'), time: '', client_name: '', address: '', phone: '', contact: '', assigned_to: [], summary: '' };
const form = useForm({ ...defaultValues });

const weekdays = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'];

const days = computed(() => {
    const monthStart = startOfMonth(currentMonth.value);
    const monthEnd = endOfMonth(monthStart);
    const start = startOfWeek(monthStart, { weekStartsOn: 0 });
    const end = endOfWeek(monthEnd, { weekStartsOn: 0 });
    return eachDayOfInterval({ start, end });
});

const appointmentsByDate = computed(() => {
    const map = {};
    for (const app of props.appointments) {
        (map[app.date] ||= []).push(app);
    }
    return map;
});

function getAssignedName(token) {
    const [type, id] = token.split(':');
    if (type === 'user') return props.users.find((u) => String(u.id) === id)?.name || 'Usuário';
    if (type === 'sector') return `Setor: ${props.sectors.find((s) => String(s.id) === id)?.name || 'Setor'}`;
    return token;
}

function handlePrevMonth() { currentMonth.value = subMonths(currentMonth.value, 1); }
function handleNextMonth() { currentMonth.value = addMonths(currentMonth.value, 1); }

function openModalForDay(day) {
    selectedDate.value = day;
    searchTermAssignees.value = '';
    editingAppointment.value = null;
    selectedAppointment.value = null;
    form.reset();
    Object.assign(form, defaultValues, { date: format(day, 'yyyy-MM-dd') });
    isModalOpen.value = true;
}

function handleDayClick(day) {
    if (isSameMonth(day, currentMonth.value)) openModalForDay(day);
}

function handleEditClick(app) {
    editingAppointment.value = app;
    searchTermAssignees.value = '';
    form.clearErrors();
    Object.assign(form, {
        date: app.date,
        time: app.time,
        client_name: app.client_name,
        address: app.address,
        phone: app.phone ? formatPhoneNumber(app.phone) : '',
        contact: app.contact,
        assigned_to: [...app.assigned_to],
        summary: app.summary || '',
    });
    isModalOpen.value = true;
}

function handleCustomerSelect(customer) {
    const mainName = customer.nome_fantasia || customer.name;
    form.client_name = mainName;
    form.address = customer.endereco || '';
    form.phone = formatPhoneNumber(customer.telefone || customer.phone_2 || '');
    form.contact = customer.contact_name || customer.contact_name_2 || mainName;
    isCustomerSearchOpen.value = false;
}

function handleAddToGoogleCalendar(app) {
    const [year, month, day] = app.date.split('-').map(Number);
    const [hour, minute] = app.time.split(':').map(Number);
    const start = new Date(year, month - 1, day, hour, minute);
    const end = new Date(start.getTime() + 60 * 60 * 1000);
    const fmt = (d) => format(d, "yyyyMMdd'T'HHmmss");
    const title = encodeURIComponent(`Visita Técnica: ${app.client_name}`);
    const dates = `${fmt(start)}/${fmt(end)}`;
    const details = encodeURIComponent(`Contato: ${app.contact}\nTelefone: ${app.phone || 'N/A'}\nResumo: ${app.summary || ''}\n\nAgendado via VendasPro`);
    const location = encodeURIComponent(app.address);
    window.open(`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${dates}&details=${details}&location=${location}`, '_blank');
}

async function triggerNotifications(appointmentId) {
    notificationState.isOpen = true;
    notificationState.isLoading = true;
    sentMessageIndexes.value = [];
    try {
        const { data } = await axios.post(`/dashboard/agenda/${appointmentId}/notify`);
        notificationState.isLoading = false;
        notificationState.isSimulated = !!data.isSimulated;
        notificationState.details = data.details || [];
        if (!data.isSimulated) toast({ title: 'Notificações Enviadas', description: 'O cliente e os técnicos foram avisados via WhatsApp.' });
    } catch (e) {
        notificationState.isOpen = false;
        notificationState.isLoading = false;
        toast({ variant: 'destructive', title: 'Erro nas Notificações' });
    }
}

function sendManualWhatsApp(detail, index) {
    const cleanPhone = detail.phone.replace(/\D/g, '');
    const phoneWithCountryCode = cleanPhone.length > 11 ? cleanPhone : `55${cleanPhone}`;
    window.open(`https://wa.me/${phoneWithCountryCode}?text=${encodeURIComponent(detail.message)}`, 'vendaspro_whatsapp');
    if (!sentMessageIndexes.value.includes(index)) sentMessageIndexes.value.push(index);
}

function statusUpdate(app, status, extra = {}) {
    router.patch(`/dashboard/agenda/${app.id}/status`, { status, ...extra }, {
        preserveScroll: true,
        onSuccess: () => { selectedAppointment.value = null; },
    });
}

function handleMarkAsCompleted() {
    if (!selectedAppointment.value) return;
    statusUpdate(selectedAppointment.value, 'completed');
    toast({ title: 'Agendamento Concluído!' });
}

function handleMarkAsCancelled() {
    if (!selectedAppointment.value || !isAdmin.value) return;
    statusUpdate(selectedAppointment.value, 'cancelled');
    toast({ variant: 'destructive', title: 'Agendamento Cancelado' });
}

function handleConfirmMissed() {
    if (!appointmentToProcess.value || !justification.value.trim()) {
        toast({ variant: 'destructive', title: 'Justificativa é obrigatória.' });
        return;
    }
    statusUpdate(appointmentToProcess.value, 'missed', { justification: justification.value.trim() });
    isJustificationDialogOpen.value = false;
    appointmentToProcess.value = null;
    justification.value = '';
}

function confirmDelete() {
    if (!appointmentToDelete.value || !isAdmin.value) return;
    router.delete(`/dashboard/agenda/${appointmentToDelete.value.id}`, {
        onSuccess: () => { selectedAppointment.value = null; isDeleteDialogOpen.value = false; appointmentToDelete.value = null; },
    });
}

function onSubmit() {
    if (editingAppointment.value) {
        form.transform((d) => ({ ...d, phone: d.phone.replace(/\D/g, '') })).put(`/dashboard/agenda/${editingAppointment.value.id}`, {
            onSuccess: () => {
                const id = editingAppointment.value.id;
                isModalOpen.value = false;
                editingAppointment.value = null;
                selectedAppointment.value = null;
                triggerNotifications(id);
            },
        });
    } else {
        form.transform((d) => ({ ...d, phone: d.phone.replace(/\D/g, '') })).post('/dashboard/agenda', {
            onSuccess: () => {
                isModalOpen.value = false;
                const createdId = page.props.flash?.created_id;
                if (createdId) triggerNotifications(createdId);
            },
        });
    }
}

const selectedDayAppointments = computed(() => {
    const key = format(selectedDate.value, 'yyyy-MM-dd');
    return (appointmentsByDate.value[key] || []).slice().sort((a, b) => a.time.localeCompare(b.time));
});

const filteredSectors = computed(() => props.sectors.filter((s) => s.name.toLowerCase().includes(searchTermAssignees.value.toLowerCase())));
const filteredUsers = computed(() => props.users.filter((u) => u.name.toLowerCase().includes(searchTermAssignees.value.toLowerCase())));

const suggestedCustomers = computed(() => {
    const term = form.client_name;
    if (!term || term.length < 2 || editingAppointment.value) return [];
    return props.customers.filter((c) => c.name.toLowerCase().includes(term.toLowerCase()) || (c.nome_fantasia || '').toLowerCase().includes(term.toLowerCase())).slice(0, 5);
});

function toggleAssignee(token) {
    const idx = form.assigned_to.indexOf(token);
    if (idx >= 0) form.assigned_to.splice(idx, 1);
    else form.assigned_to.push(token);
}

function statusBadge(status) {
    return {
        completed: { label: 'Concluído', class: 'bg-green-600/20 text-green-400 border-green-600/30' },
        missed: { label: 'Não Concluído', class: '' },
        cancelled: { label: 'Cancelado', class: 'bg-gray-600/20 text-gray-400 border-gray-600/30' },
        scheduled: { label: 'Agendado', class: '' },
    }[status] || { label: status, class: '' };
}

const fieldsDisabled = computed(() => !isAdmin.value && !!editingAppointment.value);
</script>

<template>
    <Head title="Agenda" />

    <div class="flex h-full flex-col bg-card shadow-xl rounded-2xl p-6 text-card-foreground m-4 md:m-8">
        <div class="flex items-center justify-between mb-6">
            <div>
                <h2 class="text-2xl font-bold capitalize text-foreground">{{ format(currentMonth, 'MMMM', { locale: ptBR }) }}</h2>
                <p class="text-lg text-muted-foreground">{{ format(currentMonth, 'yyyy') }}</p>
            </div>
            <div class="flex items-center gap-1">
                <Button variant="ghost" size="icon" class="rounded-lg h-10 w-10" @click="handlePrevMonth"><ChevronLeft class="h-5 w-5" /></Button>
                <Button variant="ghost" size="icon" class="rounded-lg h-10 w-10" @click="handleNextMonth"><ChevronRight class="h-5 w-5" /></Button>
            </div>
        </div>

        <div class="grid flex-1 grid-cols-7 text-center">
            <div v-for="(d, i) in weekdays" :key="i" class="flex items-center justify-center text-sm font-medium text-muted-foreground py-2 border-b">{{ d }}</div>
            <div
                v-for="day in days" :key="day.toString()"
                :class="cn('flex flex-col items-center justify-start p-2 border-t border-l aspect-[10/7] min-h-0', isSameMonth(day, currentMonth) ? 'cursor-pointer' : 'bg-muted/30')"
                @click="handleDayClick(day)"
            >
                <div :class="cn(
                    'w-8 h-8 flex items-center justify-center rounded-full text-base font-medium',
                    !isSameMonth(day, currentMonth) && 'text-muted-foreground/50',
                    !isSameDay(day, selectedDate) && isSameMonth(day, currentMonth) && 'hover:bg-accent/50',
                    isSameDay(day, selectedDate) && 'bg-primary text-primary-foreground',
                    isToday(day) && !isSameDay(day, selectedDate) && 'border-2 border-primary/50',
                )">
                    {{ format(day, 'd') }}
                </div>
                <div v-if="isSameMonth(day, currentMonth)" class="flex items-center gap-1 mt-2 h-2">
                    <div v-for="(event, index) in (appointmentsByDate[format(day, 'yyyy-MM-dd')] || []).slice(0, 3)" :key="index" :class="cn('w-2 h-2 rounded-full', ['bg-chart-1', 'bg-chart-2', 'bg-chart-3'][index % 3])" />
                </div>
            </div>
        </div>
    </div>

    <Dialog v-model:open="isModalOpen">
        <DialogContent class="sm:max-w-[425px] md:max-w-3xl flex flex-col h-[85vh]">
            <DialogHeader>
                <DialogTitle>Agenda para {{ format(selectedDate, 'dd/MM/yyyy', { locale: ptBR }) }}</DialogTitle>
                <DialogDescription>{{ isAdmin ? 'Adicione, edite ou exclua compromissos.' : 'Você pode apenas reagendar (data/hora) compromissos existentes.' }}</DialogDescription>
            </DialogHeader>
            <div class="grid flex-1 grid-cols-1 md:grid-cols-2 gap-6 py-4 overflow-y-auto">
                <div class="space-y-4">
                    <h3 class="font-semibold text-lg text-foreground">Compromissos Agendados</h3>
                    <ScrollArea class="h-full pr-4">
                        <div v-if="selectedDayAppointments.length > 0" class="space-y-4">
                            <div
                                v-for="app in selectedDayAppointments" :key="app.id"
                                :class="cn('relative group p-3 bg-muted/50 rounded-lg text-sm space-y-2 cursor-pointer', selectedAppointment?.id === app.id && !editingAppointment && 'ring-2 ring-primary')"
                                @click="!editingAppointment && (selectedAppointment = app)"
                            >
                                <div class="flex justify-between items-start">
                                    <p class="font-semibold text-base pr-20">{{ app.client_name }}</p>
                                    <div class="flex items-center gap-2 text-primary font-bold"><Clock class="h-4 w-4" />{{ app.time }}</div>
                                </div>
                                <Badge :class="statusBadge(app.status).class" :variant="['missed', 'cancelled'].includes(app.status) ? 'destructive' : 'outline'">{{ statusBadge(app.status).label }}</Badge>
                                <p class="text-muted-foreground flex items-center gap-2"><MapPin class="h-4 w-4" />{{ app.address }}</p>
                                <p class="text-muted-foreground flex items-center gap-2"><User class="h-4 w-4" />{{ app.contact }}</p>
                                <div class="flex flex-wrap gap-1 items-start">
                                    <Briefcase class="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
                                    <div class="flex flex-wrap gap-1"><Badge v-for="at in app.assigned_to" :key="at" variant="outline" class="text-[10px] py-0">{{ getAssignedName(at) }}</Badge></div>
                                </div>
                                <p v-if="app.phone" class="text-muted-foreground flex items-center gap-2"><Phone class="h-4 w-4" />{{ formatPhoneNumber(app.phone) }}</p>

                                <div class="absolute top-2 right-2 flex items-center opacity-0 group-hover:opacity-100 transition-opacity bg-muted/80 rounded-md shadow-sm border">
                                    <Button variant="ghost" size="icon" class="h-7 w-7 text-emerald-600" @click.stop="handleAddToGoogleCalendar(app)"><CalendarPlus class="h-4 w-4" /></Button>
                                    <Button variant="ghost" size="icon" class="h-7 w-7 text-primary" @click.stop="triggerNotifications(app.id)"><BellRing class="h-4 w-4" /></Button>
                                    <Button variant="ghost" size="icon" class="h-7 w-7" @click.stop="handleEditClick(app)"><Pencil class="h-4 w-4" /></Button>
                                    <Button v-if="isAdmin" variant="ghost" size="icon" class="h-7 w-7 text-destructive" @click.stop="appointmentToDelete = app; isDeleteDialogOpen = true"><Trash2 class="h-4 w-4" /></Button>
                                </div>
                            </div>
                        </div>
                        <div v-else class="flex flex-col items-center justify-center h-full text-center text-muted-foreground border-2 border-dashed rounded-lg p-8"><p>Nenhum compromisso para este dia.</p></div>
                    </ScrollArea>
                </div>
                <div>
                    <h3 class="font-semibold text-lg text-foreground mb-4">{{ editingAppointment ? 'Editar Agendamento' : 'Novo Agendamento' }}</h3>
                    <form id="appointment-form" @submit.prevent="onSubmit" class="space-y-4">
                        <div class="grid grid-cols-2 gap-3">
                            <div class="space-y-2"><Label>Data</Label><Input v-model="form.date" type="date" /></div>
                            <div class="space-y-2"><Label>Horário</Label><Input v-model="form.time" type="time" /></div>
                        </div>
                        <div class="space-y-2 relative">
                            <Label>Nome do Cliente</Label>
                            <Input v-model="form.client_name" autocomplete="off" :disabled="fieldsDisabled" @focus="isCustomerSearchOpen = true" />
                            <div v-if="isCustomerSearchOpen && suggestedCustomers.length > 0" class="absolute z-50 mt-1 w-full bg-card border rounded-md shadow-lg overflow-hidden">
                                <div v-for="customer in suggestedCustomers" :key="customer.id" class="px-4 py-2 hover:bg-accent cursor-pointer" @mousedown.prevent="handleCustomerSelect(customer)">
                                    <p class="text-sm font-semibold">{{ customer.nome_fantasia || customer.name }}</p>
                                    <p class="text-[10px] text-muted-foreground truncate">{{ customer.endereco || 'Sem endereço' }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="space-y-2"><Label>Endereço</Label><Input v-model="form.address" :disabled="fieldsDisabled" /></div>
                        <div class="space-y-2">
                            <Label>Telefone (WhatsApp)</Label>
                            <Input :model-value="form.phone" @update:modelValue="(v) => (form.phone = formatPhoneNumber(v))" :disabled="fieldsDisabled" placeholder="(00) 00000-0000" />
                        </div>
                        <div class="space-y-2"><Label>Contato na Visita</Label><Input v-model="form.contact" :disabled="fieldsDisabled" /></div>
                        <div class="space-y-2">
                            <Label>Setor/Responsável (Múltiplos)</Label>
                            <Popover :modal="false">
                                <PopoverTrigger as-child :disabled="fieldsDisabled">
                                    <Button type="button" variant="outline" class="w-full justify-start text-left h-auto min-h-10 px-3 py-2" :disabled="fieldsDisabled">
                                        <div v-if="form.assigned_to.length > 0" class="flex flex-wrap gap-1"><Badge v-for="val in form.assigned_to" :key="val" variant="secondary" class="text-[10px]">{{ getAssignedName(val) }}</Badge></div>
                                        <span v-else class="text-muted-foreground text-sm">Selecione os responsáveis</span>
                                    </Button>
                                </PopoverTrigger>
                                <PopoverContent class="w-[350px] p-0" align="start">
                                    <div class="p-2 border-b bg-background"><div class="relative"><Search class="absolute left-2 top-2.5 h-3 w-3 text-muted-foreground" /><Input v-model="searchTermAssignees" placeholder="Buscar por nome..." class="pl-7 h-8 text-xs" /></div></div>
                                    <ScrollArea class="h-[250px]">
                                        <div class="p-2 space-y-4">
                                            <div>
                                                <p class="text-[10px] font-bold text-muted-foreground uppercase px-2 mb-2">Setores</p>
                                                <div v-for="sector in filteredSectors" :key="`s-${sector.id}`" class="flex items-center space-x-2 rounded-md p-2 hover:bg-muted/50 cursor-pointer" @click="toggleAssignee(`sector:${sector.id}`)">
                                                    <Checkbox :checked="form.assigned_to.includes(`sector:${sector.id}`)" /><span class="text-sm">{{ sector.name }}</span>
                                                </div>
                                            </div>
                                            <div>
                                                <p class="text-[10px] font-bold text-muted-foreground uppercase px-2 mb-2">Colaboradores</p>
                                                <div v-for="u in filteredUsers" :key="`u-${u.id}`" class="flex items-center space-x-2 rounded-md p-2 hover:bg-muted/50 cursor-pointer" @click="toggleAssignee(`user:${u.id}`)">
                                                    <Checkbox :checked="form.assigned_to.includes(`user:${u.id}`)" /><span class="text-sm">{{ u.name }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </ScrollArea>
                                </PopoverContent>
                            </Popover>
                            <p v-if="form.errors.assigned_to" class="text-xs text-destructive">{{ form.errors.assigned_to }}</p>
                        </div>
                        <div class="space-y-2"><Label>Resumo/Notas</Label><Textarea v-model="form.summary" :disabled="fieldsDisabled" /></div>
                    </form>
                </div>
            </div>
            <DialogFooter class="pt-4 gap-2 border-t">
                <template v-if="editingAppointment">
                    <Button type="button" variant="outline" @click="editingAppointment = null; selectedAppointment = null">Cancelar</Button>
                    <Button v-if="isAdmin && selectedAppointment?.status !== 'cancelled'" type="button" variant="destructive" @click="handleMarkAsCancelled">Cancelar Visita</Button>
                    <Button type="submit" form="appointment-form">Salvar e Notificar</Button>
                </template>
                <template v-else>
                    <template v-if="selectedAppointment">
                        <Button type="button" variant="outline" class="mr-auto gap-2" @click="handleAddToGoogleCalendar(selectedAppointment)"><CalendarPlus class="h-4 w-4 text-emerald-600" /> Google Agenda</Button>
                        <Button type="button" variant="secondary" @click="handleMarkAsCompleted">Marcar Concluído</Button>
                        <Button type="button" @click="handleEditClick(selectedAppointment)">Reagendar</Button>
                        <Button v-if="isAdmin" type="button" variant="destructive" @click="appointmentToDelete = selectedAppointment; isDeleteDialogOpen = true">Excluir</Button>
                    </template>
                    <Button v-if="isAdmin || !editingAppointment" type="submit" form="appointment-form">Agendar e Notificar</Button>
                </template>
            </DialogFooter>
        </DialogContent>
    </Dialog>

    <Dialog v-model:open="notificationState.isOpen">
        <DialogContent class="sm:max-w-md">
            <DialogHeader>
                <DialogTitle class="flex items-center gap-2">
                    <Loader2 v-if="notificationState.isLoading" class="h-5 w-5 animate-spin" />
                    <AlertTriangle v-else-if="notificationState.isSimulated" class="h-5 w-5 text-yellow-500" />
                    <CheckCircle2 v-else class="h-5 w-5 text-green-500" />
                    {{ notificationState.isLoading ? 'Enviando Notificações' : (notificationState.isSimulated ? 'Configuração Pendente' : 'Notificações Enviadas') }}
                </DialogTitle>
                <DialogDescription>
                    {{ notificationState.isLoading ? 'Aguarde um momento enquanto o sistema processa os avisos.' : (notificationState.isSimulated ? 'A API automática não está configurada. Por favor, envie as mensagens manualmente abaixo.' : 'O cliente e os técnicos foram notificados com sucesso.') }}
                </DialogDescription>
            </DialogHeader>
            <div v-if="notificationState.isLoading" class="py-8 flex justify-center"><Loader2 class="h-12 w-12 animate-spin text-primary" /></div>
            <ScrollArea v-else class="max-h-[50vh] pr-4">
                <div class="space-y-3 py-2">
                    <div v-for="(detail, idx) in notificationState.details" :key="idx" class="flex flex-col gap-2 p-3 border rounded-lg bg-muted/30">
                        <div class="flex items-center justify-between">
                            <span class="text-sm font-semibold">{{ detail.name }}</span>
                            <Badge variant="outline" class="text-[10px] uppercase">{{ detail.to === 'client' ? 'Cliente' : 'Técnico' }}</Badge>
                        </div>
                        <div class="text-xs text-muted-foreground line-clamp-2 italic">"{{ detail.message }}"</div>
                        <Button
                            size="sm"
                            :variant="sentMessageIndexes.includes(idx) ? 'outline' : (notificationState.isSimulated ? 'default' : 'outline')"
                            :class="cn('w-full h-8 gap-2', sentMessageIndexes.includes(idx) && 'text-green-500 border-green-500/30 bg-green-500/5')"
                            @click="sendManualWhatsApp(detail, idx)"
                        >
                            <Check v-if="sentMessageIndexes.includes(idx)" class="h-3.5 w-3.5" /><Send v-else class="h-3.5 w-3.5" />
                            {{ sentMessageIndexes.includes(idx) ? 'Mensagem Enviada' : (notificationState.isSimulated ? 'Enviar via WhatsApp' : 'Reenviar') }}
                        </Button>
                    </div>
                </div>
            </ScrollArea>
            <DialogFooter><Button variant="outline" @click="notificationState.isOpen = false">Fechar</Button></DialogFooter>
        </DialogContent>
    </Dialog>

    <Dialog v-model:open="isJustificationDialogOpen">
        <DialogContent>
            <DialogHeader><DialogTitle>Justificar Não Conclusão</DialogTitle></DialogHeader>
            <div class="py-4"><Textarea v-model="justification" placeholder="Motivo..." rows="4" /></div>
            <DialogFooter>
                <Button variant="outline" @click="justification = ''; appointmentToProcess = null; isJustificationDialogOpen = false">Cancelar</Button>
                <Button variant="destructive" @click="handleConfirmMissed">Confirmar</Button>
            </DialogFooter>
        </DialogContent>
    </Dialog>

    <AlertDialog v-model:open="isDeleteDialogOpen">
        <AlertDialogContent>
            <AlertDialogHeader>
                <AlertDialogTitle>Excluir Agendamento?</AlertDialogTitle>
                <AlertDialogDescription>Esta ação é permanente e não pode ser desfeita.</AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
                <AlertDialogCancel @click="isDeleteDialogOpen = false; appointmentToDelete = null">Cancelar</AlertDialogCancel>
                <AlertDialogAction class="bg-destructive text-destructive-foreground hover:bg-destructive/90" @click="confirmDelete">Confirmar Exclusão</AlertDialogAction>
            </AlertDialogFooter>
        </AlertDialogContent>
    </AlertDialog>
</template>
